-- CreateEnum
CREATE TYPE "GameMode" AS ENUM ('RAPID_FIRE', 'PRECISION', 'STUDY', 'TIME_ATTACK', 'FLASHCARD_FRENZY', 'TEST_MODE');

-- AlterTable
ALTER TABLE "Quiz" ADD COLUMN     "accuracy" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "attempts" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "defaultGameMode" "GameMode" NOT NULL DEFAULT 'RAPID_FIRE';
