-- AlterTable
ALTER TABLE "User" ADD COLUMN     "averageAccuracy" DOUBLE PRECISION,
ADD COLUMN     "bio" TEXT,
ADD COLUMN     "favoriteSubject" TEXT,
ADD COLUMN     "isPublicProfile" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "joinedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "location" TEXT,
ADD COLUMN     "longestWinStreak" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "totalBeefWins" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "totalQuizzes" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "totalScore" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "website" TEXT,
ADD COLUMN     "winStreak" INTEGER NOT NULL DEFAULT 0;
